parameters:
    env(SENTRY_BACKEND): null
sentry:
    dsn: '%env(SENTRY_BACKEND)%'
    tracing:
        enabled: true
        dbal: # DB queries
            enabled: true
        cache:
            enabled: true
        twig: # templating engine
            enabled: true
