/* This file was automatically generated by the typescript:generate command. */
interface IJobRotation {
  id: number|null;
  job: IJob;
  description: string|null;
  skill1: ISkill|null;
  skill2: ISkill|null;
  skill3: ISkill|null;
  skill4: ISkill|null;
}