/* This file was automatically generated by the typescript:generate command. */
interface IAppState {
  userName: string|null;
  userAvatar: string|null;
  navigation: INavEntry[];
  skills: ISkill[];
  jobs: IJob[];
  isUser: boolean;
  isAdmin: boolean;
  frontController: string;
}