name: 🚀 Deploy to Production (SSH)

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Create .env
        uses: iamsauravsharma/create-dotenv@v1.2.0
        with:
          env-prefix: 'ENV_KEY_'
        env:
          ENV_KEY_APP_ENV: prod
          ENV_KEY_APP_SECRET: ${{ secrets.ENV_APP_SECRET }}
          ENV_KEY_ADMIN_URL: ${{ secrets.ENV_ADMIN_URL }}
          ENV_KEY_DATABASE_URL: ${{ secrets.ENV_DATABASE_URL }}
          ENV_KEY_CORS_ALLOW_ORIGIN: ${{ secrets.ENV_CORS_ALLOW_ORIGIN }}
          ENV_KEY_SENTRY_FRONTEND: ${{ secrets.SENTRY_FRONTEND }}
          ENV_KEY_SENTRY_BACKEND: ${{ secrets.SENTRY_BACKEND }}

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Cached node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn packages
        run: yarn install

      - name: Build frontend assets
        run: yarn run build

      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Remove var
        run: rm -rf var

      #
      # Deployment
      #
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }} --delete

  clear-cache:
    name: Clear Cache
    needs: deploy-prod
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Clear Cache via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SSH_PATH }}
            rm -rf var
            php80 bin/console cache:clear --env=dev
            php80 bin/console cache:clear --env=prod
