name: 🚀 Deploy to Production (SSH)

on:
  #  push:
  #    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Cached node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn packages
        run: yarn install

      - name: Build frontend assets
        run: yarn run build

      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Remove var
        run: rm -rf var

      - name: Create .env
        uses: iamsauravsharma/create-dotenv@v1.2.0
        env:
          APP_ENV: prod
          APP_SECRET: ${{ secrets.ENV_APP_SECRET }}
          ADMIN_URL: ${{ secrets.ENV_ADMIN_URL }}
          DATABASE_URL: ${{ secrets.ENV_DATABASE_URL }}
          CORS_ALLOW_ORIGIN: ${{ secrets.ENV_CORS_ALLOW_ORIGIN }}

      #
      # Deployment
      #
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}
